site_name: 客户端知识图谱
copyright: Copyright &copy; 2024 konokol.
nav:
- 首页:
  - 概述: index.md
  - 关于: pages/home/about.md
  - 学习资料: pages/home/ref.md
- Android:
  - Android知识树: pages/android/index.md
  - 基础:
    - 四大组件--Activity: pages/android/1-basic/01-Activity.md
    - 四大组件--Service: pages/android/1-basic/02-Service.md
    - 四大组件--BroadcastReceiver: pages/android/1-basic/03-BroadcastReceiver.md
    - Android GC原理: Android/1-Basic/Android-GC.md
    - Android中对集合的优化: Android/1-Basic/Android-collections.md
    - Android SQLite数据库优化: Android/1-Basic/Android-database.md
    - Android内存泄漏: Android/1-Basic/Android-memory.md
    - Android 5.0到7.0的行为变更: Android/1-Basic/Android-new-features.md
    - 理解Activity，View，Window三者关系: Android/1-Basic/Android-window.md
    - Android动画简介: Android/1-Basic/Animations.md
    - AsyncTask原理解析: Android/1-Basic/AsyncTask.md
    - ButterKnife原理解析: Android/1-Basic/ButterKnife.md
    - ContentProvider: Android/1-Basic/ContentProvider.md
    - EventBus原理解析: Android/1-Basic/EventBus.md
    - Fresco相关: Android/1-Basic/Fresco.md
    - 消息机制: Android/1-Basic/Handler.md
    - HandlerThread与IntentService: Android/1-Basic/HandlerThread&IntentService.md
    - Android 热修复原理: Android/1-Basic/Hotfix.md
    - 高效加载图片: Android/1-Basic/Image.md
    - Routing: Android/1-Basic/Routing.md
    - 序列化: Android/1-Basic/Serialization.md
    - aidl: Android/1-Basic/aidl.md
    - Android虚拟机相关: Android/1-Basic/android-virtual-machine.md
    - 事件分发机制: Android/1-Basic/event-dispatch.md
    - Fragment相关: Android/1-Basic/fragment2activity.md
    - View的绘制流程: Android/1-Basic/how-is-view-drew.md
    - keep-alive: Android/1-Basic/keep-alive.md
    - Android打包: Android/1-Basic/tools.md
  - 性能:
    - 敬请期待: none.md
  - 架构:
    - 敬请期待: none.md
  - 三方框架:
    - 敬请期待: none.md
  - Framework:
    - 源码阅读计划: pages/android/5-framework/00-android-source-code.md
    - 系统启动流程: pages/android/5-framework/01-system-boot.md
    - Activity的启动流程: pages/android/5-framework/02-activity-source-code.md
  - 工具与工程:
    - 打包流程: pages/android/6-tools/01-apk-build.md
    - 敬请期待: none.md
- Java基础:
  - 面向对象: pages/java/1-basic/00-OO.md
  - 基础:
    - 基本数据类型: pages/java/1-basic/01-primitive-data-types.md
    - 引用数据类型: pages/java/1-basic/02-refrefence-data-types.md
    - 数字和字符串: pages/java/1-basic/03-number-and-strings.md
    - 引用: pages/java/1-basic/04-references.md
    - 注解: pages/java/1-basic/05-annotations.md
    - 泛型: pages/java/1-basic/06-generics.md
    - 反射: pages/java/1-basic/07-reflation.md
    - 异常: pages/java/1-basic/08-exception.md
  - 并发:
    - 多线程: pages/java/2-concurrent/01-thread.md
    - 线程池: pages/java/2-concurrent/02-thread-pool.md
  - Java的集合框架: Java/Collections.md
  - 设计模式: Java/Design-pattern.md
  - JVM运行时数据区和Java内存模型: Java/JVM-memory-model.md
  - Java 8函数式数据处理: Java/Java-8-functional.md
  - Java 8函数式编程–––Lambda表达式: Java/Java-8-lambda.md
  - ThreadLocal原理: Java/ThreadLocal.md
  - Java单例的写法: Java/design-pattern-singleton.md
- Kotlin基础:
  - 敬请期待: pages/kotlin/none.md
- 跨平台技术:
  - 敬请期待: pages/cross-platform/none.md
- CS理论基础:
  - 算法:
    - 敬请期待: pages/cs/algorithm/none.md
  - 计算机基础:
    - 敬请期待: pages/cs/cs-basic/none.md
  - 网络:
    - HTTP协议详解: pages/cs/internet/HTTP.md
  - 操作系统:
    - 敬请期待: pages/cs/os/none.md
theme:
  language: zh
  name: material
  favicon: assets/book.png
  palette:
    primary: teal
    accent: white
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - navigation.instant
    - navigation.tabs.sticky
  plugins:
  - tags: null
    enabled: true
    tags_allowed:
    - HTML5
    - JavaScript
    - CSS
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/konokol
  - icon: fontawesome/brands/zhihu
    link: https://www.zhihu.com/people/konokol
  - icon: fontawesome/solid/envelope
    link: mailto:lijundut@foxmail.com
repo_url: https://github.com/konokol/frontend-skill-tree
repo_name: konokol/frontend-skill-tree
edit_uri: ''
markdown_extensions:
- def_list
- attr_list
extra_css:
- css/app.css
